### ISSUE TITLE
silently truncates folders at around file number 100

### ISSUE THREAD

**Issue by admackin** [fabe/gatsby-plugin-drive#18]
The [Google Drive Files API v3](https://developers.google.com/drive/api/v3/search-files) requires you to track page tokens to know whether there are more files to download. Currently the queries are truncated to the first "page" which seems to be a little over 100 files. It needs to track `nextPageToken` to handle this correctly. But it's a pain to rewrite because promises etc.

**Comment by admackin** [comment]
There is a [quick and dirty page-size solution](https://github.com/richseviora/gatsby-plugin-drive/commit/0b8a40d542077eaee19ed685a6c53f437a512cc0)

**Comment by fabe** [comment]
I added this `pageSize` param to the plugin options. Not pretty, but seems like it makes it easier to work with.

I'll close this for now.
