### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by vol-pi** [fabe/gatsby-plugin-drive#5]
when downloading many files from google drive, I quickly hit an API rate limit. Instead of the actual file the following file is created:
```
403: User Rate Limit Exceeded

The per-user limit has been reached. This may be the limit from the Developer Console or a limit from the Drive backend.

{ "error": { "errors": [ { "domain": "usageLimits", "reason": "userRateLimitExceeded", "message": "User Rate Limit Exceeded" } ], "code": 403, "message": "User Rate Limit Exceeded" } }

Suggested actions:

Raise the per-user quota in the Developer Console project.
If one user is making a lot of requests on behalf of many users of a G Suite domain, consider a Service Account with authority delegation (setting the quotaUser parameter).
Use exponential backoff.
```

This can be resolved by deleting affected files and retrying. However this is quite cumbersome for automation.

I solved it with a dirty fix: a sleep of ~1000ms right before the `getFile()` call.

```
log(`sleep for ${file.id}`);
sleep(1100);
const buffer = file.mimeType === GOOGLE_DOC ? await middleware(googleapi.getGDoc(file.id, token, exportMime)) : await googleapi.getFile(file.id, token);
[...]
const sleep = (ms) => {
  var start = new Date().getTime(), expire = start + ms;
  while (new Date().getTime() < expire) { }
  return;
}
```

Thank you for your great work on this plugin :+1:

**Comment by fabe** [comment]
I think this is something you can change in the Google developer console:

![](https://i.stack.imgur.com/yoZku.png)

Taken from [here](https://stackoverflow.com/questions/10311969/what-is-the-limit-on-google-drive-api-usage). Not sure if this is something that needs to be changed in the package code, but I'll add a note in the README. Thanks!
